
cask "affinity-designer"
cask "affinity-photo"
cask "affinity-publisher"
cask "alacritty"
cask "amethyst"
cask "appcleaner"
cask "backblaze"
cask "balenaetcher"
cask "curseforge"
cask "db-browser-for-sqlite"
cask "discord"
cask "dupeguru"
cask "filebot"
cask "font-fira-code-nerd-font"
cask "google-chrome"
cask "microsoft-remote-desktop"
cask "notion"
cask "obsidian"
cask "sensiblesidebuttons"
cask "signal"
cask "slack"
cask "smplayer"
cask "steam"
cask "sublime-merge"
cask "tad"
cask "the-unarchiver"
cask "transnomino"
cask "unnaturalscrollwheels"
cask "visual-studio-code"
cask "wireshark"
cask "xnviewmp"
cask "zotero"
mas "Cardhop", id: 1290358394
mas "Goodnotes", id: 1444383602
mas "Paprika Recipe Manager 3", id: 1303222628
mas "SonicWall Mobile Connect", id: 822514576
mas "Strongbox", id: 897283731
mas "TestFlight", id: 899247664
mas "Xcode", id: 497799835
